services:
  osservability-aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  osservability-readerprimary:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DefaultConnection=Server=sqlserver;Database=FruitDB;User Id=sa;Password=DaprSample12@=;
    ports:
      - "80"

  osservability-readersecondary:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DefaultConnection=Server=sqlserver;Database=VegetableDB;User Id=sa;Password=DaprSample12@=;
    ports:
      - "80"