services:
  osservability-aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  osser:
    environment:
    - DefaultConnection=Server=sqlserver;Database=FruitDB;User Id=sa;Password=DaprSample12@=;